### PR TITLE
Basic versioning support

### PR DESCRIPTION
**Pull request by timdp**
Quick and dirty attempt to implement #44.

### CODE REVIEW

**Comment by BenV** [comment]
+1

**Comment by Tim-B** [comment]
I haven't taken a good look at the versioning feature yet, but I was thinking it might be neat to use the NPM package version rather than having to define it separately.

We already parse the package.json file so it wouldn't be too tricky: https://github.com/Tim-B/grunt-aws-lambda/blob/master/tasks/lambda_package.js#L35

Can you think of any issues with that approach?

**Comment by timdp** [comment]
I considered it myself but then decided that Lambda's tags don't really align with npm versions. I wouldn't be opposed to the option, but I'd still like to be able to override it for tags like "prod" and "dev" as suggested in the docs; that's how I'm currently using the feature.

**Comment by IAmFledge** [comment]
Any progress on deciding whether to run with this or not? 
Keen for this functionality and was going to put it in myself before seeing this PR. If this works, be great to get it in.

**Comment by timdp** [comment]
@IAmFledge It works here, so if you're feeling adventurous, do give it a try. :wink:

**Comment by JohnBloom** [comment]
+1 This would be a really good feature to have.

**Comment by MrRogue** [comment]
+1

**Comment by tero** [comment]
+1

**Comment by IAmFledge** [comment]
Is there any reason this hasn't been merged in yet? 
I'm going to create my own fork with a variant of these changes, unless this is due in any moment.

**Comment by Tim-B** [comment]
Thanks for the pull request and feedback, support for versions and aliases has been added in the latest version.

**Pull request closed without merging**
