### PR TITLE
Added support for new lambda callback function.

### PR DESCRIPTION
**Pull request by bobhigs**
Added basic support for the new lambda callback function. See: https://aws.amazon.com/about-aws/whats-new/2016/04/aws-lambda-supports-node-js-4-3/

### CODE REVIEW

**Comment by Tim-B** [comment]
Hi Michael, thanks for the pull request!

Would you mind adding some unit tests? Otherwise I'm likely to break this in future by accident ;)

**Comment by bobhigs** [comment]
Added some unit tests. Haven't used this system before so tell me if anything needs to be changed.

**Comment by marcoscarceles** [comment]
👍

**Comment by kerrmarin** [comment]
Any progress on this?

**Comment by ssayala** [comment]
👍

**Comment by nmaves** [comment]
What are we waiting on for this ?  Anything more the community can help with?

**Comment by Tim-B** [comment]
My apologies for the delay, I've been a bit busy.

This should be included in the version I just published.

**Pull request merged**
