### PR TITLE
Fully mock up the context object to work with succeed and fail

### LINKED ISSUE #8: context.succeed() and context.fail() when using lambda_invoke
When you use `grunt lambda_invoke` on even the hello world script, it gives the error:
```sh
$ grunt lambda_invoke:HelloWorld
Running "lambda_invoke:HelloWorld" (lambda_invoke) task

Loading function
value1 = First Value
value2 = Second Value
value3 = Third Value
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.
```

I found the issue is that `context.succeed` function is not defined in the invoke.

Is this project still active?  If so I can submit a PR to fix this by fully mocking the context object as documented in the AWS Lambda docs.  Thanks!

### PR DESCRIPTION
**Pull request by jonyo**
This would resolve #8

### CODE REVIEW

**Comment by Tim-B** [comment]
Hi jayno, thanks for the pull request!

It looks like the Travis tests are failing, but there's another issue someone reported which gives a similar message to what the Travis results say. Could you confirm that the tests pass on your machine?

**Comment by jonyo** [comment]
@Tim-B the tests fail on my box, even running develop.  I think I know the problem, has to do with NPM global installation not being in the path even though it's installed globally.  I've seen other packages that require parts of npm specify it in the package.json, will try that and see if tests pass (if so I'll do a separate PR for that).

**Comment by jonyo** [comment]
@Tim-B It did fix it for my local tests, see PR #13.  If you are fine with that and merge it, I'll rebase my 2 PR's to make sure they pass with the fixed NPM dependency.

**Comment by Tim-B** [comment]
Thanks, I'll try and make time to work through your PRs this weekend.

**Pull request merged**
